import os
import json
import base64
import re
import secrets
import sqlite3
from contextlib import contextmanager
from datetime import timedelta
from functools import wraps
from pathlib import Path

import httpx
from dotenv import load_dotenv
from flask import Flask, jsonify, request, send_from_directory, session
from werkzeug.security import check_password_hash, generate_password_hash

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent
STATIC_DIR = BASE_DIR / "static"

app = Flask(__name__, static_folder=str(STATIC_DIR), static_url_path="")
INSTANCE_DIR = BASE_DIR / "instance"
INSTANCE_DIR.mkdir(exist_ok=True)
DATABASE_PATH = INSTANCE_DIR / "phuc-ai.sqlite3"
SESSION_SECRET_PATH = INSTANCE_DIR / ".session-secret"
DATABASE_URL = os.getenv("DATABASE_URL")


def load_session_secret():
    configured_secret = os.getenv("APP_SECRET_KEY")
    if configured_secret:
        return configured_secret

    if SESSION_SECRET_PATH.exists():
        return SESSION_SECRET_PATH.read_text(encoding="utf-8").strip()

    secret = secrets.token_hex(32)
    try:
        SESSION_SECRET_PATH.write_text(secret, encoding="utf-8")
    except OSError:
        if SESSION_SECRET_PATH.exists():
            return SESSION_SECRET_PATH.read_text(encoding="utf-8").strip()
        raise
    return secret


app.secret_key = load_session_secret()
app.config.update(
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SAMESITE="Lax",
    PERMANENT_SESSION_LIFETIME=timedelta(days=365),
    MAX_CONTENT_LENGTH=16 * 1024 * 1024,
)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"
ANTHROPIC_VERSION = "2023-06-01"


def get_database():
    if DATABASE_URL:
        import psycopg
        from psycopg.rows import dict_row

        return psycopg.connect(DATABASE_URL, row_factory=dict_row, connect_timeout=10)

    connection = sqlite3.connect(DATABASE_PATH)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return connection


def execute_query(connection, query, parameters=()):
    if DATABASE_URL:
        query = query.replace("?", "%s")
    return connection.execute(query, parameters)


@contextmanager
def database_connection():
    connection = get_database()
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def initialize_database():
    if DATABASE_URL:
        with database_connection() as connection:
            execute_query(
                connection,
                """
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """,
            )
            execute_query(
                connection,
                """
                CREATE TABLE IF NOT EXISTS user_history (
                    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                    sessions_json TEXT NOT NULL DEFAULT '[]',
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """,
            )
        return

    with database_connection() as connection:
        connection.executescript(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT NOT NULL UNIQUE COLLATE NOCASE,
                password_hash TEXT NOT NULL,
                created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE IF NOT EXISTS user_history (
                user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                sessions_json TEXT NOT NULL DEFAULT '[]',
                updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            """
        )


initialize_database()


def login_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        if not session.get("user_id"):
            return jsonify({"error": "Vui lòng đăng nhập để tiếp tục."}), 401
        return view(*args, **kwargs)

    return wrapped


@app.get("/")
def index():
    return send_from_directory(str(STATIC_DIR), "index.html")


@app.get("/health")
def health():
    return jsonify({"status": "ok", "service": "Phúc AI"})


def start_user_session(user):
    session.clear()
    session["user_id"] = user["id"]
    session.permanent = True
    return jsonify({"authenticated": True, "username": user["username"]})


@app.post("/api/auth/register")
def register():
    data = request.get_json(silent=True) or {}
    username = str(data.get("username") or "").strip()
    password = data.get("password") or ""

    if not re.fullmatch(r"[\w.-]{3,32}", username, flags=re.UNICODE):
        return jsonify({"error": "Tên đăng nhập cần dài 3-32 ký tự, chỉ gồm chữ, số, dấu chấm, gạch ngang hoặc gạch dưới."}), 400
    if not isinstance(password, str) or not 8 <= len(password) <= 128:
        return jsonify({"error": "Mật khẩu cần dài từ 8 đến 128 ký tự."}), 400

    try:
        with database_connection() as connection:
            cursor = execute_query(
                connection,
                "INSERT INTO users (username, password_hash) VALUES (?, ?) RETURNING id",
                (username, generate_password_hash(password)),
            )
            user = {"id": cursor.fetchone()["id"], "username": username}
            execute_query(connection, "INSERT INTO user_history (user_id) VALUES (?)", (user["id"],))
    except Exception as exc:
        if isinstance(exc, sqlite3.IntegrityError) or exc.__class__.__name__ == "UniqueViolation":
            return jsonify({"error": "Tên đăng nhập này đã được sử dụng."}), 409
        raise

    return start_user_session(user), 201


@app.post("/api/auth/login")
def login():
    data = request.get_json(silent=True) or {}
    username = str(data.get("username") or "").strip()
    password = data.get("password") or ""

    with database_connection() as connection:
        user = execute_query(
            connection,
            "SELECT id, username, password_hash FROM users WHERE username = ?",
            (username,),
        ).fetchone()

    if not user or not isinstance(password, str) or not check_password_hash(user["password_hash"], password):
        return jsonify({"error": "Tên đăng nhập hoặc mật khẩu không đúng."}), 401
    return start_user_session(user)


@app.get("/api/auth/me")
def current_user():
    user_id = session.get("user_id")
    if not user_id:
        return jsonify({"authenticated": False})

    with database_connection() as connection:
        user = execute_query(
            connection,
            "SELECT username FROM users WHERE id = ?",
            (user_id,),
        ).fetchone()
    if not user:
        session.clear()
        return jsonify({"authenticated": False})
    return jsonify({"authenticated": True, "username": user["username"]})


@app.post("/api/auth/logout")
def logout():
    session.clear()
    return jsonify({"authenticated": False})


@app.route("/api/history", methods=["GET", "PUT"])
@login_required
def account_history():
    user_id = session["user_id"]
    if request.method == "GET":
        with database_connection() as connection:
            row = execute_query(
                connection,
                "SELECT sessions_json FROM user_history WHERE user_id = ?",
                (user_id,),
            ).fetchone()
        try:
            sessions = json.loads(row["sessions_json"]) if row else []
        except (TypeError, json.JSONDecodeError):
            sessions = []
        return jsonify({"sessions": sessions})

    data = request.get_json(silent=True) or {}
    sessions = data.get("sessions")
    if not isinstance(sessions, list):
        return jsonify({"error": "Lịch sử hội thoại không hợp lệ."}), 400

    sessions_json = json.dumps(sessions, ensure_ascii=False, separators=(",", ":"))
    if len(sessions_json.encode("utf-8")) > 14 * 1024 * 1024:
        return jsonify({"error": "Lịch sử quá lớn để sao lưu."}), 413

    with database_connection() as connection:
        execute_query(
            connection,
            """
            INSERT INTO user_history (user_id, sessions_json, updated_at)
            VALUES (?, ?, CURRENT_TIMESTAMP)
            ON CONFLICT(user_id) DO UPDATE SET
                sessions_json = excluded.sessions_json,
                updated_at = CURRENT_TIMESTAMP
            """,
            (user_id, sessions_json),
        )
    return jsonify({"saved": True})


def build_system_prompt():
    return (
        "Bạn là Phúc AI, một trợ lý AI mạnh mẽ và đáng tin cậy. "
        "Luôn trả lời bằng tiếng Việt tự nhiên, trực tiếp và súc tích. "
        "Tuân thủ chính xác số lượng người dùng yêu cầu; nếu họ xin một gợi ý, chỉ đưa đúng một gợi ý. "
        "Không tự thêm danh sách dài, lời bài hát có bản quyền, hoặc chi tiết không được hỏi. "
        "Khi được hỏi xu hướng hiện tại mà không có dữ liệu trực tiếp, hãy nói rõ bạn không thể xác minh xu hướng hôm nay. "
        "Chỉ giải thích dài hoặc liệt kê nhiều lựa chọn khi người dùng yêu cầu."
    )


def normalize_messages(raw_messages):
    transformed = []
    for message in raw_messages or []:
        role = message.get("role", "user")
        if role not in {"user", "assistant"}:
            continue

        text = (message.get("text") or "").strip()
        attachments = message.get("attachments") or []

        blocks = []
        if text:
            blocks.append({"type": "text", "text": text})

        for attachment in attachments:
            kind = attachment.get("type")
            if kind == "image":
                data_url = attachment.get("dataUrl") or ""
                if not data_url.startswith("data:"):
                    continue
                header, _, encoded = data_url.partition(",")
                mime_type = "image/png"
                if ";base64" in header:
                    mime_type = header.split(":", 1)[1].split(";", 1)[0]
                try:
                    image_data = base64.b64decode(encoded)
                except Exception:
                    continue
                blocks.append(
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": mime_type,
                            "data": base64.b64encode(image_data).decode("utf-8"),
                        },
                    }
                )

        transformed.append({"role": role, "content": blocks or [{"type": "text", "text": "..."}]})

    return transformed


def extract_text_from_messages(messages):
    text_messages = []
    for item in messages:
        role = item.get("role")
        if role not in {"user", "assistant"}:
            continue
        text_parts = []
        text = (item.get("text") or "").strip()
        if text:
            text_parts.append(text)
        attachments = item.get("attachments") or []
        for attachment in attachments:
            if attachment.get("type") == "image":
                text_parts.append("[Hình ảnh đính kèm]")
        if text_parts:
            text_messages.append({"role": role, "content": "\n".join(text_parts)})
    return text_messages


def model_provider(model_name):
    name = (model_name or "").lower()
    if name.startswith("gemini"):
        return "gemini"
    if name.startswith("deepseek"):
        return "deepseek"
    if name.startswith("gpt") or name.startswith("o1") or name.startswith("o3"):
        return "openai"
    if name.startswith("claude"):
        return "anthropic"
    return "openai"


def call_gemini(model_name, messages):
    api_key = GEMINI_API_KEY
    if not api_key:
        raise RuntimeError("Missing GEMINI_API_KEY")

    model_names = [model_name]

    last_error = None
    for candidate_model in model_names:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{candidate_model}:generateContent?key={api_key}"
        payload = {
            "systemInstruction": {"parts": [{"text": build_system_prompt()}]},
            "contents": [],
            "generationConfig": {"maxOutputTokens": 768, "temperature": 0.5},
        }
        for message in extract_text_from_messages(messages):
            payload["contents"].append({
                "role": "user" if message["role"] == "user" else "model",
                "parts": [{"text": message["content"]}],
            })

        try:
            response = httpx.post(url, json=payload, timeout=60.0)
            response.raise_for_status()
            result = response.json()
            candidates = result.get("candidates") or []
            for candidate in candidates:
                parts = candidate.get("content", {}).get("parts", [])
                if parts:
                    text = "".join(part.get("text", "") for part in parts if isinstance(part, dict))
                    if text:
                        return text.strip()
            raise RuntimeError("Gemini response did not contain text")
        except httpx.HTTPStatusError as exc:
            last_error = exc
            if exc.response.status_code != 404:
                raise
    raise last_error if last_error else RuntimeError("Gemini request failed")


def call_deepseek(model_name, messages):
    api_key = DEEPSEEK_API_KEY
    if not api_key:
        raise RuntimeError("Missing DEEPSEEK_API_KEY")

    response = httpx.post(
        "https://api.deepseek.com/v1/chat/completions",
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json={
            "model": model_name,
            "messages": [
                {"role": "system", "content": build_system_prompt()},
                *[{"role": item["role"], "content": item["content"]} for item in extract_text_from_messages(messages)],
            ],
            "stream": False,
        },
        timeout=60.0,
    )
    response.raise_for_status()
    result = response.json()
    choices = result.get("choices") or []
    if not choices:
        raise RuntimeError("DeepSeek returned no choices")
    message = choices[0].get("message", {})
    return (message.get("content") or "").strip() or "Tôi không có phản hồi rõ ràng cho yêu cầu này."


def call_openai(model_name, messages):
    api_key = OPENAI_API_KEY
    if not api_key:
        raise RuntimeError("Missing OPENAI_API_KEY")

    response = httpx.post(
        "https://api.openai.com/v1/chat/completions",
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json={
            "model": model_name,
            "messages": [
                {"role": "system", "content": build_system_prompt()},
                *[{"role": item["role"], "content": item["content"]} for item in extract_text_from_messages(messages)],
            ],
        },
        timeout=60.0,
    )
    response.raise_for_status()
    result = response.json()
    choices = result.get("choices") or []
    if not choices:
        raise RuntimeError("OpenAI returned no choices")
    message = choices[0].get("message", {})
    return (message.get("content") or "").strip() or "Tôi không có phản hồi rõ ràng cho yêu cầu này."


def call_anthropic(model_name, messages):
    api_key = ANTHROPIC_API_KEY
    if not api_key:
        raise RuntimeError("Missing ANTHROPIC_API_KEY")

    normalized = normalize_messages(messages)
    response = httpx.post(
        ANTHROPIC_API_URL,
        headers={
            "x-api-key": api_key,
            "anthropic-version": ANTHROPIC_VERSION,
            "content-type": "application/json",
        },
        json={
            "model": model_name,
            "max_tokens": 1024,
            "system": build_system_prompt(),
            "messages": normalized,
        },
        timeout=60.0,
    )
    response.raise_for_status()
    result = response.json()
    text_blocks = []
    for block in result.get("content", []):
        if block.get("type") == "text":
            text_blocks.append(block.get("text", ""))
    return "\n".join(text_blocks).strip() or "Tôi không có phản hồi rõ ràng cho yêu cầu này."


def provider_error_message(provider, error):
    provider_names = {
        "gemini": "Gemini",
        "deepseek": "DeepSeek",
        "openai": "ChatGPT/OpenAI",
        "anthropic": "Claude",
    }
    name = provider_names.get(provider, "model đã chọn")

    if isinstance(error, RuntimeError) and str(error).startswith("Missing "):
        return f"Chưa cấu hình API key cho {name}. Hãy kiểm tra file .env rồi khởi động lại ứng dụng."
    if isinstance(error, httpx.HTTPStatusError):
        status = error.response.status_code
        if status in (401, 403):
            return f"{name} từ chối API key hoặc quyền truy cập. Hãy kiểm tra key và quyền của tài khoản."
        if status in (402, 429):
            return f"{name} đã hết quota hoặc credit. Hãy kiểm tra billing của nhà cung cấp."
        if status == 404:
            return f"Model {name} không khả dụng. Hãy chọn model khác được API key hỗ trợ."
        if status == 503:
            return f"{name} đang tạm thời quá tải. Hãy thử gửi lại sau ít phút."
    return f"Không thể kết nối với {name}. Hãy kiểm tra API key, quota và thử lại."


def generate_image_with_gemini(prompt):
    if not GEMINI_API_KEY:
        raise RuntimeError("Missing GEMINI_API_KEY")

    models = [
        "gemini-2.5-flash-image",
        "gemini-3-pro-image-preview",
        "gemini-3.1-flash-image-preview",
        "gemini-3.1-flash-image",
    ]
    last_error = None
    for model in models:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={GEMINI_API_KEY}"
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"responseModalities": ["TEXT", "IMAGE"]},
        }
        try:
            response = httpx.post(url, json=payload, timeout=60.0)
            response.raise_for_status()
            result = response.json()
            candidates = result.get("candidates") or []
            for candidate in candidates:
                parts = candidate.get("content", {}).get("parts", [])
                for part in parts:
                    inline_data = part.get("inlineData") or part.get("inline_data")
                    if inline_data:
                        mime = inline_data.get("mimeType") or inline_data.get("mime_type") or "image/png"
                        data = inline_data.get("data")
                        if data:
                            return f"data:{mime};base64,{data}"
            raise RuntimeError("Gemini image response did not contain image data")
        except httpx.HTTPStatusError as exc:
            last_error = exc
            if exc.response.status_code not in (404, 429):
                raise
            continue
    if last_error:
        raise last_error
    raise RuntimeError("No Gemini image model is currently available")


@app.post("/api/chat")
@login_required
def chat():
    data = request.get_json(silent=True) or {}
    model = data.get("model") or "gemini-3-flash-preview"
    raw_messages = data.get("messages") or []

    if model_provider(model) != "gemini":
        return jsonify({"error": "Phúc AI hiện chỉ hỗ trợ Gemini."}), 400
    if not raw_messages:
        return jsonify({"error": "No conversation messages were provided."}), 400

    provider = model_provider(model)
    try:
        if provider == "gemini":
            reply = call_gemini(model, raw_messages)
        elif provider == "deepseek":
            reply = call_deepseek(model, raw_messages)
        elif provider == "openai":
            reply = call_openai(model, raw_messages)
        elif provider == "anthropic":
            reply = call_anthropic(model, raw_messages)
        else:
            return jsonify({"error": "Model chưa được hỗ trợ."}), 400

        return jsonify({"reply": reply, "provider": provider, "model": model, "fallback": False})
    except Exception as exc:
        return jsonify({
            "error": provider_error_message(provider, exc),
            "provider": provider,
            "model": model,
            "fallback": False,
        }), 502


@app.post("/api/image")
@login_required
def image_generation():
    data = request.get_json(silent=True) or {}
    prompt = (data.get("prompt") or "").strip()
    if not prompt:
        return jsonify({"error": "Vui lòng nhập mô tả ảnh."}), 400

    try:
        image_data = generate_image_with_gemini(prompt)
        return jsonify({"image": image_data, "provider": "gemini", "fallback": False})
    except Exception as exc:
        return jsonify({
            "error": provider_error_message("gemini", exc),
            "provider": "gemini",
            "fallback": False,
        }), 503


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=False)
